### ISSUE TITLE
Revert 3.4 change to ruby method names

### ISSUE THREAD

**Issue by mmindenhall** [vert-x3/vertx-lang-ruby#31]
Per [this discussion thread](https://groups.google.com/forum/#!topic/vertx/CdH7AZDLvR0), ruby predicate method names were changed in version 3.4 to only end with a question mark if the method name begins with "is".  

However, it is definitely idiomatic in ruby that *all* predicate method names should end with a question mark.  This is true for core ruby (e.g., [Object](https://ruby-doc.org/core-2.3.3/Object.html)), the standard library, and 3rd party libraries/gems.

Please restore the idiomatic behavior in version 3.5.

**Comment by tsegismont** [comment]
Would you like to contribute the fix?

2017-09-08 18:27 GMT+02:00 Mark Mindenhall <notifications@github.com>:

**Comment by mmindenhall** [comment]
I looked around before filing the issue, but couldn't find the commit that changed the behavior.  I don't think that code lives in this project.  Any pointers?

**Comment by tsegismont** [comment]
I would expect the change to be needed in the templates for code generation.

2017-09-12 16:35 GMT+02:00 Mark Mindenhall <notifications@github.com>:
