### ISSUE TITLE
JRuby Compatibility Hard-Coded to 1.9

### ISSUE THREAD

**Issue by sbellware** [vert-x3/vertx-lang-ruby#5]
This line appears to hard-code JRuby compatibility to 1.9:
https://github.com/vert-x3/vertx-lang-ruby/blob/master/src/main/java/io/vertx/lang/ruby/ContainerHolder.java#L66

I would have expected that Vert.x would respect the JRUBY_OPTS environment variable, which is mechanism that JRuby itself uses to set compatibility.

If Vert.x does indeed need to set a compatibility version on the ScriptingContainer, maybe it could be done based on the value of JRUBY_OPTS.

So, when JRUBY_OPTS is "--2.0", cont.setCompatVersion(CompatVersion.RUBY2_0). And when JRUBY_OPTS is "--1.0", cont.setCompatVersion(CompatVersion.RUBY1_9).

I don't understand the internals of the JRuby language bindings, but it would seem that the CompatVersion thing would present a problem for moving beyond "legacy" versions of JRuby. The current JRuby release (JRuby 9.0.0.0) has no compatibility version setting at all. It's only Ruby 2.2.2.

PS: I wish I could help more, and submit a pull request. I haven't touched Java in many years and have no familiarity with the ecosystem, tools, build, etc. I wish I did. I'd love to be able to help the project more constructively.

Thanks,
Scott

**Comment by vietj** [comment]
we're thinking to upgrade to jruby 9K so this setting would go away. is it fine for you ?

**Comment by sbellware** [comment]
I think that would be a fine advancement for Vert.x overall. Unfortunately for us, it won't particularly matter. Our organization has decided to move away from Vert.x going forward as we feel that it seems to be geared more for a Java shop that needs to run a bit of Ruby than a Ruby shop that is running on the JVM.

**Comment by vietj** [comment]
won't fix in master as we ugpraded to JRuby 9K
